<?php
$this->renderPart('Header');
$this->renderPart('Navigation');
?>
    <div class="col d-flex flex-column h-sm-100">
        <div class="content">
            <div class="col-12 box">
                <div class="boxheader">Alle Shops</div>
                <div class="boxbody">

                    <table class="table table-borderless table_main">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Aktion</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->__get('shop') as $shop) { ?>
                            <tr>
                                <th scope="row"><?= $shop->getName() ?></th>
                                <td>
                                    <?php if ($shop->getId() != 1) { ?>
                                        <a href="https://<?= URL ?>shop/settings/edit/<?= $shop->getId() ?>"><i
                                                    class="fas fa-pen"
                                                    aria-hidden="true"></i></a>&nbsp; &nbsp;&nbsp; &nbsp;
                                        <a href="https://<?= URL ?>shop/settings/delete/<?= $shop->getId() ?>"><i
                                                    class="fas fa-trash"
                                                    aria-hidden="true"></i></a>
                                    <?php } ?>
                                </td>
                            </tr>
                        <?php } ?>

                        </tbody>
                    </table>


                </div>
                <div class="boxfooter"></div>
            </div>
            <?php
            $this->displayMSG();
            ?>

            <div class="col-12 box">
                <div class="boxheader">Neuen Shop anlegen</div>
                <div class="boxbody">


                    <form class="row g-3" action="https://<?= URL ?>shop/settings" method="POST">

                        <div class="col-md-6">
                            <label for="inputCity" class="form-label">Name des Shops</label>
                            <input type="text" class="form-control" id="inputCity" name="cat">
                        </div>

                        <div class="col-12">
                            <button type="submit" class="btn btn-primary graybutton">Anlegen</button>
                        </div>
                    </form>

                </div>
                <div class="boxfooter"></div>
            </div>


        </div>

    </div>

    </div>

<?php
$this->renderPart('Footer');
